sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql2
  database: "<%=ENV['OPENSHIFT_APP_NAME']%>"
  username: "<%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>"
  password: "<%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>"
  host:     <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>

postgresql: &postgresql
  adapter: postgresql
  database: <%=ENV['POSTGRESQL_DATABASE']%>
  username: <%=ENV['POSTGRESQL_USER']%>
  password: <%=ENV['POSTGRESQL_PASSWORD']%>
  #host:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port:     5432
  min_messages: ERROR
  reconnect: false

defaults: &defaults
  pool: 5
  timeout: 5000
  encoding: utf8
  <<: *<%= ENV['RAILS_DB'] || "postgresql" %>

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults
